<?php
    header('Content-Type: application/json');
    $_SESSION['dependencies'] = "BACKEND";
    include '../control/Dependencies.php';
    include '../constants/GraphOption.php';

    $conn = connect();
    $json_data = array();
    $current_date_time = getCurrentDate("America/Edmonton");
    $date_parser = dayAndTimeSplitter($current_date_time);
    $current_day = $date_parser[0];
    $current_time = $date_parser[1];

    if($_SESSION['graph_options'] == GraphOption::ONE_DAY || $_SESSION['graph_options'] == GraphOption::NONE)
    {
        //These variables are converted to have format of YYYY-MM-DD instead of DD-MM-YYYY in order to compare with date and time
        //generated by sql event scheduler, which will be parsed to DD-MM-YYYY after query returns
        $one_day_ago = date('Y-m-d', strtotime('-1 day', strtotime($date_parser[0])));
        $current_day = date('Y-m-d');

        //No need to specify the log interval here since event scheduler in the db is scheduled to log 
        //every 15 minutes by default
        $sql = "SELECT artist_username, price_per_share, time_recorded, date_recorded FROM artist_stock_change WHERE artist_username = ? AND date_recorded = ? ORDER BY time_recorded";
        $stmt = $conn->prepare($sql);
        $stmt->bind_param('ss', $_SESSION['selected_artist'], $one_day_ago);
        $stmt->execute();
        $result = $stmt->get_result();

        while($row = $result->fetch_assoc())
        {
            //Don't care about the seconds
            $row['time_recorded'] = substr($row['time_recorded'], 0, 5);
            $row['date_recorded'] = dateParser(toDDMMYYYY($row['date_recorded']));
            array_push($json_data, $row);
        }

        $sql = "SELECT artist_username, price_per_share, time_recorded, date_recorded FROM artist_stock_change WHERE artist_username = ? AND date_recorded = ? ORDER BY time_recorded";
        $stmt = $conn->prepare($sql);
        $stmt->bind_param('ss', $_SESSION['selected_artist'], $current_day);
        $stmt->execute();
        $result = $stmt->get_result();

        while($row = $result->fetch_assoc())
        {
            //Don't care about the seconds
            $row['time_recorded'] = substr($row['time_recorded'], 0, 5);
            $row['date_recorded'] = dateParser(toDDMMYYYY($row['date_recorded']));
            array_push($json_data, $row);
        }
    }

    closeCon($conn);

    print json_encode($json_data);
?>